const GET_GROUP_INFO = 'GET_GROUP_INFO';
const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
const REMOVE_USER_FROM_GROUP = 'REMOVE_USER_FROM_GROUP';
export default { GET_GROUP_INFO, ADD_USER_TO_GROUP, REMOVE_USER_FROM_GROUP };

